version: '3'

services:
    swagger-ui:
        container_name: swagger-container
        ports:
            - '8081:8080'
        environment:
            - BASE_URL=/swagger
            - SWAGGER_JSON=/swagger.yml
        volumes:
            - '/bar:/foo'
        image: swaggerapi/swagger-ui